### ISSUE TITLE
Sharepoint Server  - Check that documents are indexed - Config file isn't found by default

### ISSUE THREAD

**Issue by DianaJourdan** [elastic/enterprise-search-sharepoint-server-connector#40]
# Prerequisites

1. The Sharepoint Server source is added via the Admin UI.
2. The `make install_package` on the git repo for the connector was run successfully as described [here](https://github.com/elastic/enterprise-search-sharepoint-server-connector#installation). 

# Expected

`ees_sharepoint full-sync` should run and sync the docs

# Actual

After fixing the path as described [here](https://github.com/elastic/enterprise-search-team/issues/1747), the following happens:

```
2 ❯ ees_sharepoint full-sync
Traceback (most recent call last):
  File "/Users/marynacherniavska/Library/Python/3.9/bin/ees_sharepoint", line 8, in <module>
    sys.exit(main())
  File "/Users/marynacherniavska/Library/Python/3.9/lib/python/site-packages/ees_sharepoint/cli.py", line 92, in main
    run(args)
  File "/Users/marynacherniavska/Library/Python/3.9/lib/python/site-packages/ees_sharepoint/cli.py", line 100, in run
    commands[args.cmd](args).execute()
  File "/Users/marynacherniavska/Library/Python/3.9/lib/python/site-packages/ees_sharepoint/full_sync_command.py", line 16, in execute
    config = self.config
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/functools.py", line 969, in __get__
    val = self.func(instance)
  File "/Users/marynacherniavska/Library/Python/3.9/lib/python/site-packages/ees_sharepoint/base_command.py", line 85, in config
    return Configuration(file_name)
  File "/Users/marynacherniavska/Library/Python/3.9/lib/python/site-packages/ees_sharepoint/configuration.py", line 56, in __init__
    with open(file_name) as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/marynacherniavska/.local/config/sharepoint_server_connector.yml'
```

The command was only able to start this way:

```
ees_sharepoint -c sharepoint_server_connector.yml full-sync
```

**Comment by nirav-elastic** [comment]
Thanks @DianaJourdan for the details and stacktrace. Looking at the error stacktrace, it looks like the connector was ran on a MacOS which might be the reason of this behaviour. The ees_sharepoint full-sync command without -c option would work only for Linux environments. For Windows and MacOS the user needs to provide the config file via -c option.
This is also been mentioned in the README file. Kindly refer: https://github.com/elastic/enterprise-search-sharepoint-server-connector/blob/main/README.rst
