### ISSUE TITLE
Sharepoint Server - Permissions Sync isn't working

### ISSUE THREAD

**Issue by mchernyavskaya** [elastic/enterprise-search-sharepoint-server-connector#41]
# Discovered while testing https://github.com/elastic/enterprise-search-team/issues/1645

## Description

Permissions sync doesn't run successfully and throws an error.

## Steps to reproduce
1. Create Sharepoint Server source as described [here](https://github.com/elastic/enterprise-search-sharepoint-server-connector#installation)
2. Create a user on `ent-search` with permissions for Workplace Search and create an external identity via the external identities API:

```
curl --location --request POST 'http://localhost:3002/api/ws/v1/sources/{SOURCE_ID}/external_identities' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'Authorization: Basic {TOKEN}' \
--data-raw '{
  "external_user_id": "bhuvan\\administrator",
  "external_user_properties": [
    {
      "attribute_name": "_elasticsearch_username",
      "attribute_value": "enterprise_search"
    }
  ],
  "permissions": []
}
```

3. Create a user mappings file as described [here](https://github.com/elastic/enterprise-search-sharepoint-server-connector#sync-user-permissions)
4. Make sure to have this in `sharepoint_server_connector.yml`:

```
enable_document_permission: Yes
sharepoint_workplace_user_mapping: "path/to/your/file.csv"
```
5. Run the full sync:
```
ees_sharepoint -c sharepoint_server_connector.yml full-sync
```
6. Try to run the permissions sync:
```
ees_sharepoint -c sharepoint_server_connector.yml permission-sync
```

## Expected
The permissions sync should run and grab permissions for the mapped users.

## Actual
A lot of html code is outed to the console. Part of it cleaned up from html tags (will provide the full output if needed):

```
Starting the permission indexing.. Fetching the group roles for userid: 1 Fetching the group roles for userid: 4 Fetching the group roles for userid: 1073741823 GET http://localhost:3002/api/ws/v1/sources/api/ws/v1/sources/api/ws/v1/sources/624c458a6c66f75fa46e1cc2/permissions [status:404 request:0.090s] Error while removing the permissions from the workplace. Error: [404]

Elastic Enterprise Search

Enterprise Search has moved
Enterprise Search has moved into Kibana. Since version 8.0, the standalone user interface is no longer available. Manage App Search, Workplace Search, and all other Elastic features in one place!

[Open Kibana](http://localhost:5601/app/enterprise_search/overview)
Traceback (most recent call last): File "/Users/marynacherniavska/Library/Python/3.9/lib/python/site-packages/ees_sharepoint/usergroup_permissions.py", line 50, in remove_all_permissions user_permission = self.workplace_search_client.list_permissions( File "/Users/marynacherniavska/Library/Python/3.9/lib/python/site-packages/elastic_enterprise_search/client/_workplace_search.py", line 1103, in list_permissions return self.perform_request( File "/Users/marynacherniavska/Library/Python/3.9/lib/python/site-packages/elastic_enterprise_search/client/_base.py", line 187, in perform_request return self.transport.perform_request( File "/Users/marynacherniavska/Library/Python/3.9/lib/python/site-packages/elastic_transport/transport.py", line 311, in perform_request resp_status, resp_headers, data = connection.perform_request( File "/Users/marynacherniavska/Library/Python/3.9/lib/python/site-packages/elastic_transport/connection/http_urllib3.py", line 251, in perform_request self._raise_error( File "/Users/marynacherniavska/Library/Python/3.9/lib/python/site-packages/elastic_transport/connection/base.py", line 192, in _raise_error raise HTTP_EXCEPTIONS.get(status, APIError)( elastic_transport.exceptions.NotFoundError: [404]
```

At the same time, there's a stacktrace on `ent-search` side:

```
[2022-04-05T14:44:07.422+00:00][8][6336][app-server][ERROR]: [0955ecf9-31c4-4c0f-a63d-3685433cbfa9] Exception: ActionController::RoutingError: No route matches [POST] "/api/ws/v1/sources/624c458a6c66f75fa46e1cc2/permissions/administrator/add"
/usr/share/enterprise-search/lib/war/gems/gems/actionpack-5.2.7/lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call': No route matches [POST] "/api/ws/v1/sources/624c458a6c66f75fa46e1cc2/permissions/administrator/add" (ActionController::RoutingError)
	from /usr/share/enterprise-search/lib/war/gems/gems/actionpack-5.2.7/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
	from /usr/share/enterprise-search/lib/war/gems/gems/railties-5.2.7/lib/rails/rack/logger.rb:38:in `call_app'
	from /usr/share/enterprise-search/lib/war/gems/gems/railties-5.2.7/lib/rails/rack/logger.rb:26:in `block in call'
	from /usr/share/enterprise-search/lib/war/gems/gems/activesupport-5.2.7/lib/active_support/tagged_logging.rb:71:in `block in tagged'
	from /usr/share/enterprise-search/lib/war/gems/gems/activesupport-5.2.7/lib/active_support/tagged_logging.rb:28:in `tagged'
	from /usr/share/enterprise-search/lib/war/gems/gems/activesupport-5.2.7/lib/active_support/tagged_logging.rb:71:in `tagged'
	from /usr/share/enterprise-search/lib/war/gems/gems/railties-5.2.7/lib/rails/rack/logger.rb:26:in `call'
	from /usr/share/enterprise-search/lib/war/lib/middleware/silencer_middleware.class:9:in `call'
	from /usr/share/enterprise-search/lib/war/gems/gems/actionpack-5.2.7/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
	from /usr/share/enterprise-search/lib/war/lib/middleware/request_id_middleware.class:11:in `call'
	from /usr/share/enterprise-search/lib/war/gems/gems/rack-2.1.4/lib/rack/method_override.rb:24:in `call'
	from /usr/share/enterprise-search/lib/war/gems/gems/rack-2.1.4/lib/rack/runtime.rb:24:in `call'
	from /usr/share/enterprise-search/lib/war/gems/gems/actionpack-5.2.7/lib/action_dispatch/middleware/executor.rb:14:in `call'
	from /usr/share/enterprise-search/lib/war/gems/gems/rack-2.1.4/lib/rack/sendfile.rb:113:in `call'
	from /usr/share/enterprise-search/lib/war/lib/middleware/stats_middleware.class:10:in `call'
	from /usr/share/enterprise-search/lib/war/lib/middleware/external_host_middleware.class:26:in `call'
	from /usr/share/enterprise-search/lib/war/gems/gems/railties-5.2.7/lib/rails/engine.rb:524:in `call'
	from /usr/share/enterprise-search/lib/war/vendor/fishwife-servlet/lib/fishwife/rack_servlet.rb:74:in `service'

[2022-04-05T14:44:07.434+00:00][8][6336][action_controller][INFO]: Processing by ErrorsController#not_found as HTML
```

**Comment by nirav-elastic** [comment]
Thanks @mchernyavskaya , @serenachou for the details. This is because the Permissions endpoint has been changed from 8.x i.e. before 8.x it was [/permissions](https://www.elastic.co/guide/en/workplace-search/7.16/workplace-search-document-permissions-api.html#add) endpoint, but now it has been changed to [/external_identities](https://www.elastic.co/guide/en/workplace-search/current/workplace-search-document-permissions-api.html). Also, the [Python library](https://pypi.org/project/elastic-enterprise-search/) is still on 7.17 and [8.0](https://github.com/elastic/enterprise-search-python/blob/v8.1.0a1/CONTRIBUTING.md) is still not out and hence we could not use this new endpoints. Hence, the current version of the connector does not support Enterprise Search versions 8 and above, which we will call out in the README.

However, I've a concern that whether this Python library will be backward compatible with 7.x along with 8.x, depending on which we might have to tweak our dependencies and implementation.

**Comment by serenachou** [comment]
Backwards compatibility will not be provided per the clients team. Can you give us an updated game plan on how you plan to handle this situation @nirav-elastic ?

**Comment by serenachou** [comment]
8.2 is available per Seth. https://github.com/elastic/enterprise-search-python/releases/tag/v8.2.0

**Comment by praveen-elastic** [comment]
Hi @mchernyavskaya, @serenachou Can we close this issue if you've verified that permission sync is working now ?
